services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Atul@123
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Atul@123
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    networks:
      - ecomm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pAtul@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  ecom-inventory-service:
    build: .
    container_name: ecom-inventory-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Atul@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8084
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ecomm-network
    restart: always

networks:
  ecomm-network:
    driver: bridge